export const defaults = {
 eventName:'ECVerse 2026', eyebrow:'EKOONPOINT ENTERTAINMENT PRESENTS', tagline:'ONE NIGHT. EVERY SOUND. ALL OF US.', intro:'Ikorodu, this is your moment. Music, movement and the kind of memories that live long after the final song.', date:'2026-12-19T19:00:00+01:00', dateLabel:'19 DECEMBER 2026', timeLabel:'7 PM', venue:'Ebute Ferry Terminal, Ikorodu, Lagos', ticketUrl:'', ticketText:'Get your ticket', ticketNote:'Ticket prices change monthly. Check the official link for the current price.', announcement:'The countdown is on. ECVerse returns to Ikorodu.', announcementEnabled:true, heroImage:'/images/1000725996.jpg', logo:'/images/eko logo.jpg', contactEmail:'', contactPhone:'+2349076413769', whatsappNumber:'2349076413769', aboutTitle:'The city comes alive.', aboutText:'ECVerse brings a bold mix of Afrobeats, Fuji, DJs and the people who make a night unforgettable. Come ready to sing, dance and be part of the story.', feedbackTitle:'Help shape the next chapter', feedbackText:'Were you at the Mara Edition? Tell us what stayed with you and what you want from ECVerse this year.', feedbackEnabled:true, artistsEnabled:true, aboutEnabled:true, partnersEnabled:true, socialEnabled:true,
 artists:[
 {name:'FOLA',role:'LIVE PERFORMANCE',image:'/images/1000634592.jpg',bio:'FOLA brings heartfelt vocals and a fresh Afro-R&B pulse to ECVerse. Expect a set made for singing every word with the crowd.'},
 {name:'SHODAY',role:'LIVE PERFORMANCE',image:'/images/1000634585.jpg',bio:'Shoday’s melody-led Afrobeats and infectious energy are built for a night like this. Get ready for an electric crowd connection.'},
 {name:'KS1 MALAIKA',role:'FUJI ICON',image:'/images/1000707352.jpg',bio:'A celebrated voice in Fuji music, KS1 Malaika brings rich rhythm and the unmistakable spirit of a live Fuji performance.'},
 {name:'MARTINSFEELZ',role:'LIVE PERFORMANCE',image:'/images/1000716624.jpg',bio:'Rapper, singer and songwriter Martinsfeelz adds his vibrant blend of melody and rhythm to the ECVerse stage.'},
 {name:'DJ 4KERTY',role:'ON THE DECKS',image:'/images/1000634586.jpg',bio:'DJ 4Kerty takes the decks to keep the energy moving between moments and all through the night.'},
 {name:'DJ FERRA',role:'ON THE DECKS',image:'/images/1000689857.jpg',bio:'DJ Ferra brings the mixes and momentum for a dance floor that refuses to slow down.'},
 {name:'CDJ PSYCHE',role:'ON THE DECKS',image:'/images/1000707353.jpg',bio:'CDJ Psyche joins the lineup with a high-energy set to carry the ECVerse atmosphere late into the night.'},
 {name:'MYSTERY FUJI ARTIST',role:'SPECIAL REVEAL',image:'/images/1000725996.jpg',bio:'One more Fuji artist is joining the story. The reveal is coming — watch this space.'}
 ],
 actions:[{label:'Become a Vendor',subject:'ECVerse 2026 Vendor Enquiry',destination:'whatsapp',enabled:true},{label:'Be a Part of This Story',subject:'ECVerse 2026 Collaboration Enquiry',destination:'email',enabled:true},{label:'Sponsor',subject:'ECVerse 2026 Sponsorship Enquiry',destination:'whatsapp',enabled:true},{label:'Showcase Your Brand',subject:'ECVerse 2026 Brand Showcase Enquiry',destination:'email',enabled:true}],
 socials:[{name:'Instagram',url:'',enabled:true},{name:'Facebook',url:'',enabled:true},{name:'X',url:'',enabled:true},{name:'YouTube',url:'',enabled:true},{name:'Threads',url:'',enabled:true},{name:'TikTok',url:'',enabled:true}], footerText:'Made for the moments we remember.'
};
